// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.baeldung.protobuf;

/**
 * Protobuf enum {@code protobuf.PersonType}
 */
public enum PersonType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HOME = 0;</code>
   */
  HOME(0),
  /**
   * <code>WORK = 1;</code>
   */
  WORK(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>HOME = 0;</code>
   */
  public static final int HOME_VALUE = 0;
  /**
   * <code>WORK = 1;</code>
   */
  public static final int WORK_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PersonType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PersonType forNumber(int value) {
    switch (value) {
      case 0: return HOME;
      case 1: return WORK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PersonType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PersonType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PersonType>() {
          public PersonType findValueByNumber(int number) {
            return PersonType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.baeldung.protobuf.AddressBookProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final PersonType[] VALUES = values();

  public static PersonType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PersonType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protobuf.PersonType)
}

